export const GET_INTERNSHIPS = "GET_INTERNSHIPS";
export const ADD_INTERNSHIP = "ADD_INTERNSHIP";
export const GET_PROMOTED_INTERNSHIPS = "GET_PROMOTED_INTERNSHIPS";
export const GET_SEARCHED_INTERNSHIPS = "GET_SEARCHED_INTERNSHIPS";